package no.nav.foreldrepenger.regler.uttak.fastsetteperiode.grunnlag;

import java.util.Set;

public enum DokumentasjonVurdering {
    SYKDOM_SØKER_DOKUMENTERT,
    SYKDOM_ANNEN_FORELDER_DOKUMENTERT,
    INNLEGGELSE_SØKER_DOKUMENTERT,
    INNLEGGELSE_ANNEN_FORELDER_DOKUMENTERT,
    INNLEGGELSE_BARN_DOKUMENTERT,
    HV_OVELSE_DOKUMENTERT,
    NAV_TILTAK_DOKUMENTERT,
    MORS_AKTIVITET_DOKUMENTERT_AKTIVITET,
    MORS_AKTIVITET_DOKUMENTERT_IKKE_AKTIVITET,
    MORS_AKTIVITET_IKKE_DOKUMENTERT,
    ER_ALENEOMSORG,
    ER_BARE_SØKER_RETT,
    TIDLIG_OPPSTART_FEDREKVOTE_DOKUMENTERT
    ;

    public boolean erGyldigGrunnForTidligOppstart() {
        return Set.of(SYKDOM_ANNEN_FORELDER_DOKUMENTERT,
            INNLEGGELSE_ANNEN_FORELDER_DOKUMENTERT,
            MORS_AKTIVITET_DOKUMENTERT_AKTIVITET, ER_ALENEOMSORG, ER_BARE_SØKER_RETT, TIDLIG_OPPSTART_FEDREKVOTE_DOKUMENTERT).contains(this);
    }
}
